### ISSUE TITLE
Disable transfer progress output in Maven

### ISSUE THREAD

**Issue by colinphill-mdsol** [pitch-io/clojure-dependabot#24]
While testing this action and debugging our configuration for it, my team has found it difficult to read the log output, because a large amount of it consists of transfer progress indicators, such as this:

```
  Progress (4): 24/58 kB | 20/55 kB | 20/109 kB | 4.1/41 kB
  Progress (4): 24/58 kB | 20/55 kB | 20/109 kB | 8.2/41 kB
  Progress (4): 24/58 kB | 20/55 kB | 20/109 kB | 12/41 kB 
  Progress (4): 24/58 kB | 20/55 kB | 20/109 kB | 16/41 kB
  Progress (4): 24/58 kB | 20/55 kB | 20/109 kB | 20/41 kB
  Progress (4): 24/58 kB | 20/55 kB | 20/109 kB | 24/41 kB
  Progress (4): 24/58 kB | 20/55 kB | 20/109 kB | 28/41 kB
  Progress (4): 24/58 kB | 20/55 kB | 20/109 kB | 32/41 kB
  Progress (4): 24/58 kB | 24/55 kB | 20/109 kB | 32/41 kB
  Progress (4): 24/58 kB | 28/55 kB | 20/109 kB | 32/41 kB
  Progress (4): 28/58 kB | 28/55 kB | 20/109 kB | 32/41 kB
  Progress (4): 32/58 kB | 28/55 kB | 20/109 kB | 32/41 kB
  Progress (4): 32/58 kB | 28/55 kB | 25/109 kB | 32/41 kB
  Progress (4): 32/58 kB | 28/55 kB | 29/109 kB | 32/41 kB
  Progress (4): 32/58 kB | 28/55 kB | 33/109 kB | 32/41 kB
  Progress (4): 32/58 kB | 28/55 kB | 33/109 kB | 36/41 kB
```

This could be suppressed by passing Maven the `--no-transfer-progress` flag (which only disables this specific output) or the `--batch-mode` flag (which does that and also prevents Maven from ever prompting for input, just in case).

**Comment by luigigubello** [comment]
Nice! I will work on this improvement soon, thank you :))

**Comment by luigigubello** [comment]
@colinphill-mdsol Unfortunately I cannot use `--batch-mode` because this GitHub Action greps the Maven output, but I have added the flag `-ntp, --no-transfer-progress` to reduce the noise in the logs. I hope this can improve your UX :)
